# Generated by Django 4.1.4 on 2022-12-15 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_posts_postcomments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="real",
            field=models.ForeignKey(
                help_text="reel commented on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to="core.reel",
                verbose_name="comment on",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commenter",
                to=settings.AUTH_USER_MODEL,
                verbose_name="commented by",
            ),
        ),
    ]
