# Generated by Django 4.1.4 on 2022-12-15 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_comment_real_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date commented"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="real",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to="core.reel",
                verbose_name="comment on",
            ),
        ),
    ]
